### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by EvickaStudio** [EvickaStudio/24-Fire-REST-API#1]
- [x] Add async Support
- [x] Add other 24fire.de Endpoints
- [x] Add more Options
- [x] Add more Comments and Wiki
- [x] Modular structure

**Comment by EvickaStudio** [comment]
# Current Status

Added:
- Async Support
- `24Fire+` endpoints
- Made source code more modular for quick editing
